### ISSUE TITLE
Cannot able to use api key as a environment variable.

### ISSUE THREAD

**Issue by Appunram** [urbanclap-engg/smart-docs-parser#8]
I need to keep my google cloud vision api key secured. so Iam using .env variables. But I can't able to use env variables inside default.json file.

**Comment by SourabhJaz** [comment]
Yes, that support is missing currently.
Feel free to raise a PR for that change. It's currently fetched in the function ```getAPIKeyFromConfig``` 
You can build the support to pass an optional param ```ocr_api_key``` to ```extractDocumentDetailsFromImage```
