### ISSUE TITLE
Not working after deployment

### ISSUE THREAD

**Issue by Appunram** [urbanclap-engg/smart-docs-parser#9]
I tried using this package after deployment , but its not working . Every time its giving me this
 {raw_text: [], is_document_valid: false, document_details: {}}

**Comment by SourabhJaz** [comment]
Hey @Appunram I hope you've added a valid API key in config/ folder as mentioned in the readme?

**Comment by Appunram** [comment]
Thanks for your reply. Api key is valid. It's working fine in local but it's not working after deployment.

**Comment by SourabhJaz** [comment]
After deployment does your repo has a top level `config/` folder with` default.json` file?
Try checking that once

**Comment by SourabhJaz** [comment]
Did it work @Appunram ?
As long as your deployed repo has top level config/ folder with key in default file the project should work.
